name: Build Motorola Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y \
            git bc bison flex zip curl \
            libssl-dev libelf-dev \
            gcc-aarch64-linux-gnu \
            gcc-arm-linux-gnueabi \
            python3

      - name: Download Clang r383902
        run: |
          mkdir -p $HOME/toolchains
          cd $HOME/toolchains
          git clone --depth=1 https://github.com/kdrag0n/proton-clang clang

      - name: Build Kernel
        env:
          ARCH: arm64
          SUBARCH: arm64
          PATH: ${{ github.workspace }}/../toolchains/clang/bin:${{ env.PATH }}
        run: |
          export PATH=$HOME/toolchains/clang/bin:$PATH

          make O=out \
          ARCH=arm64 \
          hawaiipl-perd_defconfig

          make -j$(nproc) \
          O=out \
          ARCH=arm64 \
          CC=clang \
          CROSS_COMPILE=aarch64-linux-gnu- \
          CROSS_COMPILE_ARM32=arm-linux-gnueabi-

      - name: Upload Kernel
        uses: actions/upload-artifact@v4
        with:
          name: kernel
          path: |
            out/arch/arm64/boot/Image*
            out/.config
